# Generated by Django 6.0.4 on 2026-04-22 20:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Aguardando'), ('running', 'Processando'), ('done', 'Concluído'), ('error', 'Erro')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LinkResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('page_title', models.CharField(blank=True, default='', max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('error_msg', models.CharField(blank=True, default='', max_length=512)),
                ('response_ms', models.IntegerField(blank=True, help_text='Tempo de resposta em ms', null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.report')),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
                'ordering': ['id'],
            },
        ),
    ]
